### ISSUE TITLE
Issue trying to run Inethi GUI

### ISSUE THREAD

**Issue by rodrijfa** [pieterhop/inethi-gui#9]
I am having this issue when im trying to run INETHI GUI on ubuntu. 

rodrijfa@rodrijfa-HP-ENVY-TS-14-Sleekbook:~/INETHI/gui-installer$ npm start

> inethi@1.0.1 start
> electron-forge start

/home/rodrijfa/INETHI/gui-installer/node_modules/listr2/dist/index.cjs:90
    this.path = [...task.listr.path ?? [], task.title].join(" > ");
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/rodrijfa/INETHI/gui-installer/node_modules/@electron-forge/cli/dist/electron-forge.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by keeganwhite** [comment]
hi there can you please show me your npm version and let me know what version of ubuntu you are using
